import React, { Component } from 'react';
import AllColors from './AllColors/AllColors.js';

class Chipes extends Component {
  render() {
    return (
      <div>
        <AllColors colorName="GRAY"
          foxColor0={{ backgroundColor: "#f8f9fa" }}
          foxColor1={{ backgroundColor: "#f1f3f5" }}
          foxColor2={{ backgroundColor: "#e9ecef" }}
          foxColor3={{ backgroundColor: "#dee2e6" }}
          foxColor4={{ backgroundColor: "#ced4da" }}
          foxColor5={{ backgroundColor: "#adb5bd" }}
          foxColor6={{ backgroundColor: "#868e96" }}
          foxColor7={{ backgroundColor: "#495057" }}
          foxColor8={{ backgroundColor: "#343a40" }}
          foxColor9={{ backgroundColor: "#212529" }}
          foxName0="GRAY 0"
          foxName1="GRAY 1"
          foxName2="GRAY 2"
          foxName3="GRAY 3"
          foxName4="GRAY 4"
          foxName5="GRAY 5"
          foxName6="GRAY 6"
          foxName7="GRAY 7"
          foxName8="GRAY 8"
          foxName9="GRAY 9"
          foxSharp0="#f8f9fa"
          foxSharp1="#f1f3f5"
          foxSharp2="#e9ecef"
          foxSharp3="#dee2e6"
          foxSharp4="#ced4da"
          foxSharp5="#adb5bd"
          foxSharp6="#868e96"
          foxSharp7="#495057"
          foxSharp8="#343a40"
          foxSharp9="#212529"
        />
        <AllColors colorName="RED"
          foxColor0={{ backgroundColor: "#fff5f5" }}
          foxColor1={{ backgroundColor: "#ffe3e3" }}
          foxColor2={{ backgroundColor: "#ffc9c9" }}
          foxColor3={{ backgroundColor: "#ffa8a8" }}
          foxColor4={{ backgroundColor: "#ff8787" }}
          foxColor5={{ backgroundColor: "#ff6b6b" }}
          foxColor6={{ backgroundColor: "#fa5252" }}
          foxColor7={{ backgroundColor: "#f03e3e" }}
          foxColor8={{ backgroundColor: "#e03131" }}
          foxColor9={{ backgroundColor: "#c92a2a" }}
          foxName0="RED 0"
          foxName1="RED 1"
          foxName2="RED 2"
          foxName3="RED 3"
          foxName4="RED 4"
          foxName5="RED 5"
          foxName6="RED 6"
          foxName7="RED 7"
          foxName8="RED 8"
          foxName9="RED 9"
          foxSharp0="#fff5f5"
          foxSharp1="#ffe3e3"
          foxSharp2="#ffc9c9"
          foxSharp3="#ffa8a8"
          foxSharp4="#ff8787"
          foxSharp5="#ff6b6b"
          foxSharp6="#fa5252"
          foxSharp7="#f03e3e"
          foxSharp8="#e03131"
          foxSharp9="#c92a2a"
        />
        <AllColors colorName="PINK"
          foxColor0={{ backgroundColor: "#fff0f6" }}
          foxColor1={{ backgroundColor: "#ffdeeb" }}
          foxColor2={{ backgroundColor: "#fcc2d7" }}
          foxColor3={{ backgroundColor: "#faa2c1" }}
          foxColor4={{ backgroundColor: "#f783ac" }}
          foxColor5={{ backgroundColor: "#f06595" }}
          foxColor6={{ backgroundColor: "#e64980" }}
          foxColor7={{ backgroundColor: "#d6336c" }}
          foxColor8={{ backgroundColor: "#c2255c" }}
          foxColor9={{ backgroundColor: "#a61e4d" }}
          foxName0="PINK 0"
          foxName1="PINK 1"
          foxName2="PINK 2"
          foxName3="PINK 3"
          foxName4="PINK 4"
          foxName5="PINK 5"
          foxName6="PINK 6"
          foxName7="PINK 7"
          foxName8="PINK 8"
          foxName9="PINK 9"
          foxSharp0="#fff0f6"
          foxSharp1="#ffdeeb"
          foxSharp2="#fcc2d7"
          foxSharp3="#faa2c1"
          foxSharp4="#f783ac"
          foxSharp5="#f06595"
          foxSharp6="#e64980"
          foxSharp7="#d6336c"
          foxSharp8="#c2255c"
          foxSharp9="#a61e4d"
        />
        <AllColors colorName="GRAPE"
          foxColor0={{ backgroundColor: "#f8f0fc" }}
          foxColor1={{ backgroundColor: "#f3d9fa" }}
          foxColor2={{ backgroundColor: "#eebefa" }}
          foxColor3={{ backgroundColor: "#e599f7" }}
          foxColor4={{ backgroundColor: "#da77f2" }}
          foxColor5={{ backgroundColor: "#cc5de8" }}
          foxColor6={{ backgroundColor: "#be4bdb" }}
          foxColor7={{ backgroundColor: "#ae3ec9" }}
          foxColor8={{ backgroundColor: "#9c36b5" }}
          foxColor9={{ backgroundColor: "#862e9c" }}
          foxName0="GRAPE 0"
          foxName1="GRAPE 1"
          foxName2="GRAPE 2"
          foxName3="GRAPE 3"
          foxName4="GRAPE 4"
          foxName5="GRAPE 5"
          foxName6="GRAPE 6"
          foxName7="GRAPE 7"
          foxName8="GRAPE 8"
          foxName9="GRAPE 9"
          foxSharp0="#f8f0fc"
          foxSharp1="#f3d9fa"
          foxSharp2="#eebefa"
          foxSharp3="#e599f7"
          foxSharp4="#da77f2"
          foxSharp5="#cc5de8"
          foxSharp6="#be4bdb"
          foxSharp7="#ae3ec9"
          foxSharp8="#9c36b5"
          foxSharp9="#862e9c"
        />
        <AllColors colorName="VIOLET"
          foxColor0={{ backgroundColor: "#f3f0ff" }}
          foxColor1={{ backgroundColor: "#e5dbff" }}
          foxColor2={{ backgroundColor: "#d0bfff" }}
          foxColor3={{ backgroundColor: "#b197fc" }}
          foxColor4={{ backgroundColor: "#9775fa" }}
          foxColor5={{ backgroundColor: "#845ef7" }}
          foxColor6={{ backgroundColor: "#7950f2" }}
          foxColor7={{ backgroundColor: "#7048e8" }}
          foxColor8={{ backgroundColor: "#6741d9" }}
          foxColor9={{ backgroundColor: "#5f3dc4" }}
          foxName0="VIOLET 0"
          foxName1="VIOLET 1"
          foxName2="VIOLET 2"
          foxName3="VIOLET 3"
          foxName4="VIOLET 4"
          foxName5="VIOLET 5"
          foxName6="VIOLET 6"
          foxName7="VIOLET 7"
          foxName8="VIOLET 8"
          foxName9="VIOLET 9"
          foxSharp0="#f3f0ff"
          foxSharp1="#e5dbff"
          foxSharp2="#d0bfff"
          foxSharp3="#b197fc"
          foxSharp4="#9775fa"
          foxSharp5="#845ef7"
          foxSharp6="#7950f2"
          foxSharp7="#7048e8"
          foxSharp8="#6741d9"
          foxSharp9="#5f3dc4"
        />
        <AllColors colorName="INDIGO"
          foxColor0={{ backgroundColor: "#edf2ff" }}
          foxColor1={{ backgroundColor: "#dbe4ff" }}
          foxColor2={{ backgroundColor: "#bac8ff" }}
          foxColor3={{ backgroundColor: "#91a7ff" }}
          foxColor4={{ backgroundColor: "#748ffc" }}
          foxColor5={{ backgroundColor: "#5c7cfa" }}
          foxColor6={{ backgroundColor: "#4c6ef5" }}
          foxColor7={{ backgroundColor: "#4263eb" }}
          foxColor8={{ backgroundColor: "#3b5bdb" }}
          foxColor9={{ backgroundColor: "#364fc7" }}
          foxName0="INDIGO 0"
          foxName1="INDIGO 1"
          foxName2="INDIGO 2"
          foxName3="INDIGO 3"
          foxName4="INDIGO 4"
          foxName5="INDIGO 5"
          foxName6="INDIGO 6"
          foxName7="INDIGO 7"
          foxName8="INDIGO 8"
          foxName9="INDIGO 9"
          foxSharp0="#edf2ff"
          foxSharp1="#dbe4ff"
          foxSharp2="#bac8ff"
          foxSharp3="#91a7ff"
          foxSharp4="#748ffc"
          foxSharp5="#5c7cfa"
          foxSharp6="#4c6ef5"
          foxSharp7="#4263eb"
          foxSharp8="#3b5bdb"
          foxSharp9="#364fc7"
        />
        <AllColors colorName="BLUE"
          foxColor0={{ backgroundColor: "#e7f5ff" }}
          foxColor1={{ backgroundColor: "#d0ebff" }}
          foxColor2={{ backgroundColor: "#a5d8ff" }}
          foxColor3={{ backgroundColor: "#74c0fc" }}
          foxColor4={{ backgroundColor: "#4dabf7" }}
          foxColor5={{ backgroundColor: "#339af0" }}
          foxColor6={{ backgroundColor: "#228be6" }}
          foxColor7={{ backgroundColor: "#1c7ed6" }}
          foxColor8={{ backgroundColor: "#1971c2" }}
          foxColor9={{ backgroundColor: "#1864ab" }}
          foxName0="BLUE 0"
          foxName1="BLUE 1"
          foxName2="BLUE 2"
          foxName3="BLUE 3"
          foxName4="BLUE 4"
          foxName5="BLUE 5"
          foxName6="BLUE 6"
          foxName7="BLUE 7"
          foxName8="BLUE 8"
          foxName9="BLUE 9"
          foxSharp0="#e7f5ff"
          foxSharp1="#d0ebff"
          foxSharp2="#a5d8ff"
          foxSharp3="#74c0fc"
          foxSharp4="#4dabf7"
          foxSharp5="#339af0"
          foxSharp6="#228be6"
          foxSharp7="#1c7ed6"
          foxSharp8="#1971c2"
          foxSharp9="#1864ab"
        />
        <AllColors colorName="CYAN"
          foxColor0={{ backgroundColor: "#e3fafc" }}
          foxColor1={{ backgroundColor: "#c5f6fa" }}
          foxColor2={{ backgroundColor: "#99e9f2" }}
          foxColor3={{ backgroundColor: "#66d9e8" }}
          foxColor4={{ backgroundColor: "#3bc9db" }}
          foxColor5={{ backgroundColor: "#22b8cf" }}
          foxColor6={{ backgroundColor: "#15aabf" }}
          foxColor7={{ backgroundColor: "#1098ad" }}
          foxColor8={{ backgroundColor: "#0c8599" }}
          foxColor9={{ backgroundColor: "#0b7285" }}
          foxName0="CYAN 0"
          foxName1="CYAN 1"
          foxName2="CYAN 2"
          foxName3="CYAN 3"
          foxName4="CYAN 4"
          foxName5="CYAN 5"
          foxName6="CYAN 6"
          foxName7="CYAN 7"
          foxName8="CYAN 8"
          foxName9="CYAN 9"
          foxSharp0="#e3fafc"
          foxSharp1="#c5f6fa"
          foxSharp2="#99e9f2"
          foxSharp3="#66d9e8"
          foxSharp4="#3bc9db"
          foxSharp5="#22b8cf"
          foxSharp6="#15aabf"
          foxSharp7="#1098ad"
          foxSharp8="#0c8599"
          foxSharp9="#0b7285"
        />
        <AllColors colorName="TEAL"
          foxColor0={{ backgroundColor: "#e6fcf5" }}
          foxColor1={{ backgroundColor: "#c3fae8" }}
          foxColor2={{ backgroundColor: "#96f2d7" }}
          foxColor3={{ backgroundColor: "#63e6be" }}
          foxColor4={{ backgroundColor: "#38d9a9" }}
          foxColor5={{ backgroundColor: "#20c997" }}
          foxColor6={{ backgroundColor: "#12b886" }}
          foxColor7={{ backgroundColor: "#0ca678" }}
          foxColor8={{ backgroundColor: "#099268" }}
          foxColor9={{ backgroundColor: "#087f5b" }}
          foxName0="TEAL 0"
          foxName1="TEAL 1"
          foxName2="TEAL 2"
          foxName3="TEAL 3"
          foxName4="TEAL 4"
          foxName5="TEAL 5"
          foxName6="TEAL 6"
          foxName7="TEAL 7"
          foxName8="TEAL 8"
          foxName9="TEAL 9"
          foxSharp0="#e6fcf5"
          foxSharp1="#c3fae8"
          foxSharp2="#96f2d7"
          foxSharp3="#63e6be"
          foxSharp4="#38d9a9"
          foxSharp5="#20c997"
          foxSharp6="#12b886"
          foxSharp7="#0ca678"
          foxSharp8="#099268"
          foxSharp9="#087f5b"
        />
        <AllColors colorName="GREEN"
          foxColor0={{ backgroundColor: "#ebfbee" }}
          foxColor1={{ backgroundColor: "#d3f9d8" }}
          foxColor2={{ backgroundColor: "#b2f2bb" }}
          foxColor3={{ backgroundColor: "#8ce99a" }}
          foxColor4={{ backgroundColor: "#69db7c" }}
          foxColor5={{ backgroundColor: "#51cf66" }}
          foxColor6={{ backgroundColor: "#40c057" }}
          foxColor7={{ backgroundColor: "#37b24d" }}
          foxColor8={{ backgroundColor: "#2f9e44" }}
          foxColor9={{ backgroundColor: "#2b8a3e" }}
          foxName0="GREEN 0"
          foxName1="GREEN 1"
          foxName2="GREEN 2"
          foxName3="GREEN 3"
          foxName4="GREEN 4"
          foxName5="GREEN 5"
          foxName6="GREEN 6"
          foxName7="GREEN 7"
          foxName8="GREEN 8"
          foxName9="GREEN 9"
          foxSharp0="#ebfbee"
          foxSharp1="#d3f9d8"
          foxSharp2="#b2f2bb"
          foxSharp3="#8ce99a"
          foxSharp4="#69db7c"
          foxSharp5="#51cf66"
          foxSharp6="#40c057"
          foxSharp7="#37b24d"
          foxSharp8="#2f9e44"
          foxSharp9="#2b8a3e"
        />
        <AllColors colorName="LIME"
          foxColor0={{ backgroundColor: "#f4fce3" }}
          foxColor1={{ backgroundColor: "#e9fac8" }}
          foxColor2={{ backgroundColor: "#d8f5a2" }}
          foxColor3={{ backgroundColor: "#c0eb75" }}
          foxColor4={{ backgroundColor: "#a9e34b" }}
          foxColor5={{ backgroundColor: "#94d82d" }}
          foxColor6={{ backgroundColor: "#82c91e" }}
          foxColor7={{ backgroundColor: "#74b816" }}
          foxColor8={{ backgroundColor: "#66a80f" }}
          foxColor9={{ backgroundColor: "#5c940d" }}
          foxName0="LIME 0"
          foxName1="LIME 1"
          foxName2="LIME 2"
          foxName3="LIME 3"
          foxName4="LIME 4"
          foxName5="LIME 5"
          foxName6="LIME 6"
          foxName7="LIME 7"
          foxName8="LIME 8"
          foxName9="LIME 9"
          foxSharp0="#f4fce3"
          foxSharp1="#e9fac8"
          foxSharp2="#d8f5a2"
          foxSharp3="#c0eb75"
          foxSharp4="#a9e34b"
          foxSharp5="#94d82d"
          foxSharp6="#82c91e"
          foxSharp7="#74b816"
          foxSharp8="#66a80f"
          foxSharp9="#5c940d"
        />
        <AllColors colorName="YELLOW"
          foxColor0={{ backgroundColor: "#fff9db" }}
          foxColor1={{ backgroundColor: "#fff3bf" }}
          foxColor2={{ backgroundColor: "#ffec99" }}
          foxColor3={{ backgroundColor: "#ffe066" }}
          foxColor4={{ backgroundColor: "#ffd43b" }}
          foxColor5={{ backgroundColor: "#fcc419" }}
          foxColor6={{ backgroundColor: "#fab005" }}
          foxColor7={{ backgroundColor: "#f59f00" }}
          foxColor8={{ backgroundColor: "#f08c00" }}
          foxColor9={{ backgroundColor: "#e67700" }}
          foxName0="YELLOW 0"
          foxName1="YELLOW 1"
          foxName2="YELLOW 2"
          foxName3="YELLOW 3"
          foxName4="YELLOW 4"
          foxName5="YELLOW 5"
          foxName6="YELLOW 6"
          foxName7="YELLOW 7"
          foxName8="YELLOW 8"
          foxName9="YELLOW 9"
          foxSharp0="#fff9db"
          foxSharp1="#fff3bf"
          foxSharp2="#ffec99"
          foxSharp3="#ffe066"
          foxSharp4="#ffd43b"
          foxSharp5="#fcc419"
          foxSharp6="#fab005"
          foxSharp7="#f59f00"
          foxSharp8="#f08c00"
          foxSharp9="#e67700"
        />
        <AllColors colorName="ORANGE"
          foxColor0={{ backgroundColor: "#fff4e6" }}
          foxColor1={{ backgroundColor: "#ffe8cc" }}
          foxColor2={{ backgroundColor: "#ffd8a8" }}
          foxColor3={{ backgroundColor: "#ffc078" }}
          foxColor4={{ backgroundColor: "#ffa94d" }}
          foxColor5={{ backgroundColor: "#ff922b" }}
          foxColor6={{ backgroundColor: "#fd7e14" }}
          foxColor7={{ backgroundColor: "#f76707" }}
          foxColor8={{ backgroundColor: "#e8590c" }}
          foxColor9={{ backgroundColor: "#d9480f" }}
          foxName0="ORANGE 0"
          foxName1="ORANGE 1"
          foxName2="ORANGE 2"
          foxName3="ORANGE 3"
          foxName4="ORANGE 4"
          foxName5="ORANGE 5"
          foxName6="ORANGE 6"
          foxName7="ORANGE 7"
          foxName8="ORANGE 8"
          foxName9="ORANGE 9"
          foxSharp0="#fff4e6"
          foxSharp1="#ffe8cc"
          foxSharp2="#ffd8a8"
          foxSharp3="#ffc078"
          foxSharp4="#ffa94d"
          foxSharp5="#ff922b"
          foxSharp6="#fd7e14"
          foxSharp7="#f76707"
          foxSharp8="#e8590c"
          foxSharp9="#d9480f"
        />
      </div>
    );
  }
}

export default Chipes;